spring:
  main:
    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  banner:
    location: 'classpath:templates/banner.txt'
server:
  port: '${MANAPI_PROJECT_PORT}'